-- Script SQL pour ajouter les colonnes de publication aux communes
-- À exécuter sur la base de données BD_RESULTAT_PRESIDENTIELLE_2025

USE BD_RESULTAT_PRESIDENTIELLE_2025;
GO

-- Ajouter la colonne NUM_UTIL (numéro utilisateur) à TBL_COM
IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_NAME = 'TBL_COM' AND COLUMN_NAME = 'NUM_UTIL'
)
BEGIN
    ALTER TABLE TBL_COM ADD NUM_UTIL NVARCHAR(255) NULL;
    PRINT 'Colonne NUM_UTIL ajoutée à TBL_COM';
END
ELSE
BEGIN
    PRINT 'Colonne NUM_UTIL existe déjà dans TBL_COM';
END
GO

-- Ajouter la colonne STAT_PUB (statut publication) à TBL_COM
IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_NAME = 'TBL_COM' AND COLUMN_NAME = 'STAT_PUB'
)
BEGIN
    ALTER TABLE TBL_COM ADD STAT_PUB NVARCHAR(255) NULL;
    PRINT 'Colonne STAT_PUB ajoutée à TBL_COM';
END
ELSE
BEGIN
    PRINT 'Colonne STAT_PUB existe déjà dans TBL_COM';
END
GO

-- Créer la table d'historique de publication des communes
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'COMMUNE_PUBLICATION_HISTORY')
BEGIN
    CREATE TABLE COMMUNE_PUBLICATION_HISTORY (
        id NVARCHAR(255) NOT NULL PRIMARY KEY,
        COMMUNE_ID NVARCHAR(255) NOT NULL,
        ACTION NVARCHAR(255) NOT NULL,
        USER_ID NVARCHAR(255) NOT NULL,
        TIMESTAMP DATETIME2 NOT NULL DEFAULT GETDATE(),
        DETAILS NVARCHAR(MAX) NULL
    );
    PRINT 'Table COMMUNE_PUBLICATION_HISTORY créée';
END
ELSE
BEGIN
    PRINT 'Table COMMUNE_PUBLICATION_HISTORY existe déjà';
END
GO

-- Ajouter les foreign keys si elles n'existent pas
IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
    WHERE CONSTRAINT_NAME = 'FK_TBL_COM_NUM_UTIL'
)
BEGIN
    ALTER TABLE TBL_COM 
    ADD CONSTRAINT FK_TBL_COM_NUM_UTIL 
    FOREIGN KEY (NUM_UTIL) REFERENCES users(id) ON DELETE NO ACTION ON UPDATE NO ACTION;
    PRINT 'Foreign key FK_TBL_COM_NUM_UTIL ajoutée';
END
GO

IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
    WHERE CONSTRAINT_NAME = 'FK_COMMUNE_PUBLICATION_HISTORY_COMMUNE_ID'
)
BEGIN
    ALTER TABLE COMMUNE_PUBLICATION_HISTORY 
    ADD CONSTRAINT FK_COMMUNE_PUBLICATION_HISTORY_COMMUNE_ID 
    FOREIGN KEY (COMMUNE_ID) REFERENCES TBL_COM(id) ON DELETE NO ACTION ON UPDATE NO ACTION;
    PRINT 'Foreign key FK_COMMUNE_PUBLICATION_HISTORY_COMMUNE_ID ajoutée';
END
GO

IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
    WHERE CONSTRAINT_NAME = 'FK_COMMUNE_PUBLICATION_HISTORY_USER_ID'
)
BEGIN
    ALTER TABLE COMMUNE_PUBLICATION_HISTORY 
    ADD CONSTRAINT FK_COMMUNE_PUBLICATION_HISTORY_USER_ID 
    FOREIGN KEY (USER_ID) REFERENCES users(id) ON DELETE NO ACTION ON UPDATE NO ACTION;
    PRINT 'Foreign key FK_COMMUNE_PUBLICATION_HISTORY_USER_ID ajoutée';
END
GO

PRINT 'Migration terminée avec succès !';
GO

